"""
RetailFlow Product Master Data

Master product catalog used across the RetailFlow platform.

Used by:
- POS Batch Generator
- Inventory Pipeline
- Supply Chain
- Demand Forecasting
- Gold Analytics
"""

from __future__ import annotations

PRODUCTS = [
    {
        "product_id": "PRD0001",
        "product_name": "Amul Full Cream Milk 1L",
        "category": "Groceries",
        "subcategory": "Dairy",
        "brand": "Amul",
        "supplier_id": "SUP001",
        "unit_price_cents": 6800,
        "currency": "INR",
        "unit": "Litre",
        "tax_rate": 5,
        "reorder_level": 50,
    },
    {
        "product_id": "PRD0002",
        "product_name": "Fortune Basmati Rice 5kg",
        "category": "Groceries",
        "subcategory": "Rice",
        "brand": "Fortune",
        "supplier_id": "SUP002",
        "unit_price_cents": 67500,
        "currency": "INR",
        "unit": "Bag",
        "tax_rate": 5,
        "reorder_level": 25,
    },
    {
        "product_id": "PRD0003",
        "product_name": "Apple iPhone 16",
        "category": "Electronics",
        "subcategory": "Mobile",
        "brand": "Apple",
        "supplier_id": "SUP003",
        "unit_price_cents": 8999000,
        "currency": "INR",
        "unit": "Piece",
        "tax_rate": 18,
        "reorder_level": 5,
    },
    {
        "product_id": "PRD0004",
        "product_name": "Samsung Galaxy S25",
        "category": "Electronics",
        "subcategory": "Mobile",
        "brand": "Samsung",
        "supplier_id": "SUP003",
        "unit_price_cents": 7499000,
        "currency": "INR",
        "unit": "Piece",
        "tax_rate": 18,
        "reorder_level": 8,
    },
    {
        "product_id": "PRD0005",
        "product_name": "Nike Air Zoom Pegasus",
        "category": "Sports",
        "subcategory": "Footwear",
        "brand": "Nike",
        "supplier_id": "SUP004",
        "unit_price_cents": 1249900,
        "currency": "INR",
        "unit": "Pair",
        "tax_rate": 12,
        "reorder_level": 15,
    },
    {
        "product_id": "PRD0006",
        "product_name": "Adidas Football",
        "category": "Sports",
        "subcategory": "Equipment",
        "brand": "Adidas",
        "supplier_id": "SUP004",
        "unit_price_cents": 199900,
        "currency": "INR",
        "unit": "Piece",
        "tax_rate": 12,
        "reorder_level": 30,
    },
    {
        "product_id": "PRD0007",
        "product_name": "Sony WH-1000XM5",
        "category": "Electronics",
        "subcategory": "Audio",
        "brand": "Sony",
        "supplier_id": "SUP005",
        "unit_price_cents": 2999000,
        "currency": "INR",
        "unit": "Piece",
        "tax_rate": 18,
        "reorder_level": 10,
    },
    {
        "product_id": "PRD0008",
        "product_name": "LG Smart TV 55 Inch",
        "category": "Electronics",
        "subcategory": "Television",
        "brand": "LG",
        "supplier_id": "SUP005",
        "unit_price_cents": 5899900,
        "currency": "INR",
        "unit": "Piece",
        "tax_rate": 18,
        "reorder_level": 5,
    },
    {
        "product_id": "PRD0009",
        "product_name": "Puma Running T-Shirt",
        "category": "Fashion",
        "subcategory": "Apparel",
        "brand": "Puma",
        "supplier_id": "SUP004",
        "unit_price_cents": 149900,
        "currency": "INR",
        "unit": "Piece",
        "tax_rate": 12,
        "reorder_level": 20,
    },
    {
        "product_id": "PRD0010",
        "product_name": "Nestle KitKat",
        "category": "Groceries",
        "subcategory": "Chocolate",
        "brand": "Nestle",
        "supplier_id": "SUP001",
        "unit_price_cents": 3000,
        "currency": "INR",
        "unit": "Piece",
        "tax_rate": 5,
        "reorder_level": 100,
    },
]