import streamlit as st
import plotly.express as px
import pandas as pd

from dashboard.config import get_storage_options
from dashboard.data_loader import load_dataset


@st.cache_data(ttl=300)
def get_gold(dataset):
    storage_options = get_storage_options()
    return load_dataset(
        dataset,
        storage_options,
    )


st.title("Demand Forecast")
st.caption(
    "7-day demand forecast generated by the RetailFlow forecasting pipeline"
)


try:
    forecast = get_gold("demand_forecast")

    forecast["date"] = pd.to_datetime(
        forecast["date"]
    )

    # --------------------------------------------------
    # FILTERS
    # --------------------------------------------------

    col1, col2 = st.columns(2)

    stores = sorted(
        forecast["store_id"].unique().tolist()
    )

    products = sorted(
        forecast["product_id"].unique().tolist()
    )

    with col1:
        selected_store = st.selectbox(
            "Store",
            ["All Stores"] + stores,
        )

    with col2:
        selected_product = st.selectbox(
            "Product",
            ["All Products"] + products,
        )

    filtered_forecast = forecast.copy()

    if selected_store != "All Stores":
        filtered_forecast = filtered_forecast[
            filtered_forecast["store_id"]
            == selected_store
        ]

    if selected_product != "All Products":
        filtered_forecast = filtered_forecast[
            filtered_forecast["product_id"]
            == selected_product
        ]

    # --------------------------------------------------
    # KPI CARDS
    # --------------------------------------------------

    total_forecast = (
        filtered_forecast["predicted_demand"]
        .sum()
    )

    average_daily_forecast = (
        filtered_forecast["predicted_demand"]
        .mean()
    )

    peak_daily_forecast = (
        filtered_forecast["predicted_demand"]
        .max()
    )

    forecast_days = (
        filtered_forecast["date"]
        .nunique()
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Forecast Demand",
            f"{total_forecast:,.2f}",
        )

    with col2:
        st.metric(
            "Average Daily Demand",
            f"{average_daily_forecast:,.2f}",
        )

    with col3:
        st.metric(
            "Peak Daily Demand",
            f"{peak_daily_forecast:,.2f}",
        )

    with col4:
        st.metric(
            "Forecast Days",
            forecast_days,
        )

    st.divider()

    # --------------------------------------------------
    # FORECAST TREND
    # --------------------------------------------------

    st.subheader("Forecast Demand Trend")

    if filtered_forecast.empty:
        st.warning(
            "No forecast data matches the selected filters."
        )
    else:
        forecast_daily = (
            filtered_forecast
            .groupby("date", as_index=False)
            .agg(
                predicted_demand=(
                    "predicted_demand",
                    "sum",
                )
            )
        )

        forecast_chart = px.line(
            forecast_daily,
            x="date",
            y="predicted_demand",
            markers=True,
            labels={
                "date": "Forecast Date",
                "predicted_demand": "Predicted Demand",
            },
        )

        forecast_chart.update_layout(
            hovermode="x unified",
        )

        st.plotly_chart(
            forecast_chart,
            use_container_width=True,
        )

    # --------------------------------------------------
    # PRODUCT FORECAST
    # --------------------------------------------------

    st.subheader("Forecast by Product")

    product_forecast = (
        filtered_forecast
        .groupby(
            [
                "product_id",
            ],
            as_index=False,
        )
        .agg(
            forecast_demand=(
                "predicted_demand",
                "sum",
            )
        )
        .sort_values(
            "forecast_demand",
            ascending=False,
        )
    )

    product_chart = px.bar(
        product_forecast,
        x="product_id",
        y="forecast_demand",
        labels={
            "product_id": "Product",
            "forecast_demand": "7-Day Forecast",
        },
    )

    st.plotly_chart(
        product_chart,
        use_container_width=True,
    )

    # --------------------------------------------------
    # FORECAST TABLE
    # --------------------------------------------------

    st.subheader("Forecast Detail")

    forecast_display = (
        filtered_forecast
        .sort_values(
            [
                "date",
                "store_id",
                "product_id",
            ]
        )
        .copy()
    )

    forecast_display["date"] = (
        forecast_display["date"]
        .dt.strftime("%Y-%m-%d")
    )

    forecast_display[
        "predicted_demand"
    ] = forecast_display[
        "predicted_demand"
    ].round(2)

    st.dataframe(
        forecast_display,
        use_container_width=True,
        hide_index=True,
    )

    st.success(
        "Demand Forecast loaded successfully."
    )

except Exception as exc:
    st.error(
        "Unable to load Demand Forecast."
    )
    st.exception(exc)