# =============================================================================
# RetailFlow Spark Configuration
# Delta Lake Edition
# =============================================================================

# -----------------------------------------------------------------------------
# Spark Cluster
# -----------------------------------------------------------------------------

spark.master                              spark://spark-master:7077
spark.app.name                            RetailFlow


# Memory Controls (Prevents Docker Executor Crashes) 
# ----------------------------------------------------------------------------- 
spark.driver.memory               1g
spark.executor.memory             1g

# -----------------------------------------------------------------------------
# Performance
# -----------------------------------------------------------------------------

spark.sql.shuffle.partitions              4
spark.default.parallelism                 4


# -----------------------------------------------------------------------------
# Serialization
# -----------------------------------------------------------------------------

spark.serializer                          org.apache.spark.serializer.KryoSerializer


# -----------------------------------------------------------------------------
# Structured Streaming
# -----------------------------------------------------------------------------

spark.sql.streaming.forceDeleteTempCheckpointLocation=true


# -----------------------------------------------------------------------------
# Delta Lake
# -----------------------------------------------------------------------------

spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension

spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog


# -----------------------------------------------------------------------------
# Spark Packages
# -----------------------------------------------------------------------------

spark.jars.packages=\
io.delta:delta-spark_2.12:3.2.0,\
org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4,\
org.apache.hadoop:hadoop-aws:3.3.4,\
com.amazonaws:aws-java-sdk-bundle:1.12.262


# -----------------------------------------------------------------------------
# MinIO (S3A)
# -----------------------------------------------------------------------------

spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

spark.hadoop.fs.s3a.path.style.access=true

spark.hadoop.fs.s3a.connection.ssl.enabled=false

# -----------------------------------------------------------------------------
# Prometheus Monitoring
# -----------------------------------------------------------------------------

spark.ui.prometheus.enabled              true
spark.sql.streaming.metricsEnabled      true
spark.metrics.namespace                  ${spark.app.name}